# Site settings
title: Nirbhay Kumar
name: Nirbhay Kumar

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://automateddeveloper.blogspot.com/
 - title: GitHub
   url: https://github.com/robhinds
 - title: StackOverflow
   url: https://stackoverflow.com/users/9158817/nirbhay-kumar
 - title: LinkedIn
   url: https://www.linkedin.com/in/nirbhay-kumar-751558170/

#Any buzzword skills you want to include
skills:
- Python 
- Javascript
- HTML
- CSS
- Ruby on Rails
- Chef


#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required

 - title: Project Trainee(Chef)
   start: 2020
   end: Current
   employer: Msys Technologies
   description: Working on a range of functional and technical roles.

#Education is required
education:
 - level: B.Tech
   date: 2016
   subject: Computer Science With Specialization in Open Source And Open Standards
   school: University of Petroleum and Energy Studies

#This section is optional (as is the image link below)
Udacity:
   
   courses:
    - title: Udacity Bertelsmann Tech Scholar
      optionalimage: https://drive.google.com/file/d/1b1Il-r2uLD1W860OvmstF7YgqDrAWFVf/view?usp=sharing
      date: November, 2019
    

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute


#List of interesting Github repo/projects to include - optional


#Stackoverflow flair is optional

intro: |
  Looking for a position that will allow me to improve my current programming, communication and teamwork skills as well as to enhance my knowledge about new and emerging trends in the dynamic IT sector.


theme: jekyll-theme-dinky
